### ISSUE TITLE
Neuvector mirrored-prometheus-exporter:5.1.3 is not mirrored

### ISSUE THREAD

**Issue by selvamt94** [rancher/image-mirror#397]
The following image is not mirrored, can you please check.
https://github.com/rancher/image-mirror/pull/395

neuvector@NV-Ubuntu1604-Automation:~$ docker pull rancher/mirrored-prometheus-exporter:5.1.3
Error response from daemon: pull access denied for rancher/mirrored-prometheus-exporter, repository does not exist or may require 'docker login'

**Comment by superseb** [comment]
@selvamt94 The repository `rancher/mirrored-prometheus-exporter` does not seem to exist in Docker Hub. Did you file a request to have it created before you submitted the PR to add the image to be mirrored?

**Comment by selvamt94** [comment]
@superseb ` rancher/mirrored-prometheus-exporter` new component that need to be mirrored. May be there is no repository for this image. Let me create new issue to create one.

**Comment by superseb** [comment]
The correct destination is `rancher/mirrored-neuvector-prometheus-exporter` and is working (https://hub.docker.com/r/rancher/mirrored-neuvector-prometheus-exporter/tags)
