### ISSUE TITLE
Automate adding images from chart as source

### ISSUE THREAD

**Issue by superseb** [rancher/image-mirror#437]
The current implementation of automation is based on the "add tag to existing image" approach, meaning that you can provide images and tags and the logic will add if they do not already exists. As we only allow automated PRs for existing images, the logic will prevent from adding new images to the file (only add tags for images that are already present).

Later on logic was added to have a source of images/tags that can be looked up (for example, github releases or registries) and with that collected data, the workflow "add tag to existing images" is launched. 

The downside of the current approach is that we only allow for a list of images that require the same tag (usually from the same source). This means that if we have multiple images in a "release", we can't process that in a single request/PR. Currently we have multiple sources and images that all create separate PRs that make up one release.

For example, cilium uses quite a few different images with different release versions. The idea for this issue is to:

- Implement Helm chart as a new source for images/tags for a component (example project cilium, example source Cilium Helm chart)
- Retrieve Helm chart and use `helm template` with configurable values to get the correct rendered YAMLs
- Extract images from rendered YAMLs
- Feed the list of images + tags into a workflow to create the PR to add missing tags (we are still not adding new images)

Example mock up code:

```
# Lookup latest Helm chart from `index.yaml`, for this example hardcoded version
$ wget https://helm.cilium.io/cilium-1.14.0.tgz
# Helm template and extract images
$ helm template --set hubble.ui.enabled=true --set hubble.relay.enabled=true --set hubble.enabled=true --set azure.enabled=true --set envoy.enabled=true cilium-1.14.0.tgz  |  yq '..|.image? | select(.)' | sort -u | awk -F'@' '{ print $1 }'| sort -u
---
quay.io/cilium/cilium-envoy:v1.25.9-f039e2bd380b7eef2f2feea5750676bb36133699
quay.io/cilium/cilium:v1.14.0
quay.io/cilium/hubble-relay:v1.14.0
quay.io/cilium/hubble-ui-backend:v0.12.0
quay.io/cilium/hubble-ui:v0.12.0
quay.io/cilium/operator-azure:v1.14.0
# Launch workflow with comma separated list of images/tags to be processed (this is different from the current logic)
$ gh workflow run add-tag-to-existing-image.yml --ref $GITHUB_REF_NAME -f input=quay.io/cilium/cilium-envoy:v1.25.9-f039e2bd380b7eef2f2feea5750676bb36133699,quay.io/cilium/cilium:v1.14.0,quay.io/cilium/hubble-relay:v1.14.0,quay.io/cilium/hubble-ui-backend:v0.12.0,quay.io/cilium/hubble-ui:v0.12.0,quay.io/cilium/operator-azure:v1.14.0
```

**Comment by rbrtbnfgl** [comment]
that's seem to be right. Could be an idea to have a script logic where we can add command and the output will be used?

**Comment by superseb** [comment]
@rbrtbnfgl Can you share what Helm values we support for cilium? I can use that for testing the functionality to collect the images.

**Comment by superseb** [comment]
Closing since https://github.com/rancher/image-mirror/pull/489 is merged
