### ISSUE TITLE
Add support for risc-v (and plan for platform addition in general)

### ISSUE THREAD

**Issue by brandond** [rancher/image-mirror#502]
We are working in the background to add risc-v support to k3s at https://github.com/k3s-io/k3s/issues/7151. However, one of the challenges of this effort is lack of risc-v platform support in rancher-mirrored images.

While we could simply add this to the arch list, this would change the multi-arch digest for any tags that we currently mirror that have this platform available. We should figure out how to add this platform to only new tags, in a way that is minimally disruptive to the list maintenance process, and can be reused when adding new platforms in the future.

One possibility would be to
1. Add a new config file that tracks `platform:start:end` - where either or both start and end may be unspecified to indicate minimum and maximum values for the respective options. 
2. Existing platforms would be listed with an empty start and end date.
3. Use the output of `git blame --date=unix images-list` to determine when an entry was added
4. Add the platform to the list to be mirrored if the entry is newer than that platform's start date, and older than the end date

Note that we are evaluating when the entry was added to the list, NOT when the entry was published to the source registry. This approach should work as long as we continue to not modify existing list entries, such that `git blame` properly indicates the correct date for the addition of the entry.

**Comment by brandond** [comment]
cc @superseb for thoughts

**Comment by superseb** [comment]
Seems like the same issue as in https://github.com/rancher/image-mirror/issues/379#issuecomment-1766043893, where we want to switch to sync all archs. First question to be answered is if we want to mirror archs that we don't "support" (if we want to combine efforts).

If yes, we can sync all archs and use a simpler approach like copying the current `images-list` at the moment we switch to determine if the image/tag needs the old or new approach.

If no, we need something as described in this issue. We could still simply copy the current `images-list` to `images-list-before-risc` and compare in the script if it's new or not. But I assume that having duplicated lists might not be what we want?

**Comment by brandond** [comment]
I guess I'm just concerned that using blame ties us to being exceptionally careful about never modifying existing rows. If something gets accidentally touched by a newer commit, it'll get promoted up to all arch. As long as we're careful I guess it should be ok.

**Comment by superseb** [comment]
If we add a CI check for modifying existing rows as part of this, it should be good.

**Comment by brandond** [comment]
unstale. @superseb are you up for this, if not I'll take a shot.

**Comment by brandond** [comment]
Bad stalebot.

**Comment by brandond** [comment]
still in the backlog

**Comment by brandond** [comment]
no

**Comment by henryys** [comment]
> unstale. @superseb are you up for this, if not I'll take a shot.

hi，brandond, i'm very care about this method，How is the progress of this adaptation work？
