### ISSUE TITLE
Support more version filter(s) in Helm chart image retrieval

### ISSUE THREAD

**Issue by superseb** [rancher/image-mirror#506]
This comes from https://github.com/rancher/image-mirror/pull/504#issuecomment-1782458653.

In case of Longhorn, they have a stable (v1.4.x) and latest (v1.5.x) release. In current logic, we only get the latest from Helm. (it determines the latest available by not providing any version to the `helm` commands). We can easily add support for this but the question is regarding the design of the configuration.

Three options I can think of:
- Add a new source configuration name called `helm` and specify a `versionFilter`, this aligns with the other sources. Possible downside is that you need to copy paste the blocks for `helm-latest` and `helm`. This will also result in multiple PRs as they are different blocks.
- Add a new configuration option `versionFilter` to `helm-latest`. Possible downside is that you need to copy paste the blocks with and without this `versionFilter`. This will also result in multiple PRs as they are different blocks.
- Add a new configuration option `additionalVersionFilter` to `helm-latest`. This will be used, after getting the images for latest, to get additional images using the filters from this array. This will result in a single PR with all images for all charts. Possible downside is that images from multiple chart versions get combined while this is not desirable.

We could also combine 1 & 3 or 2 & 3 to give the user the option for how they want the PRs to end up (combined or separate).

**Comment by superseb** [comment]
Thoughts @brandond ?

**Comment by brandond** [comment]
Does LH keep the stable and latest charts in different repos, or are they all in the same repo? If they're in different repos, it feels like we should just handle these separately - despite the irritation of having to field multiple automated PRs.

**Comment by superseb** [comment]
They are in the same repository.
