### ISSUE TITLE
Please add sonobuoy image

### ISSUE THREAD

**Issue by masap** [rancher/image-mirror#737]
We would like to add `https://github.com/vmware-tanzu/sonobuoy` repository into image-mirror.
We are using the repository to collect data from customer for Supportability Review Project (https://github.com/rancher/supportability-review).
Previously we pull/push to rancher repository (`rancher/mirrored-sonobuoy-sonobuoy`) by using Github workflow job (https://github.com/rancher/supportability-review/blob/main/.github/workflows/release.yaml#L439-L502).
We would like to migrate the pull/push task into this repositories task.

CC @Anarkis @vherr

**Comment by masap** [comment]
Hello @Anarkis. Previously we push new `sonobuoy` image by using Supportability Review workflow. But we can't use the workflow any more because EIO team decided to prohibit `int128/docker-manifest-create-action@v2`. So please add `sonobuoy` image to this repo.

**Comment by Anarkis** [comment]
> Hello @Anarkis. Previously we push new `sonobuoy` image by using Supportability Review workflow. But we can't use the workflow any more because EIO team decided to prohibit `int128/docker-manifest-create-action@v2`. So please add `sonobuoy` image to this repo.

Hi @masap did you read the README? https://github.com/rancher/image-mirror?tab=readme-ov-file#mirroring-external-images-into-rancher-repo-on-dockerhub 
there you can find all the info related to the repo.

Also, `sonobuoy` image is already present in the repo: https://github.com/rancher/image-mirror/blob/3510ea651608e1e65ec2c4c039e8b6aba42bccf8/images-list#L1984

And published into rancher dockerhub https://hub.docker.com/r/rancher/mirrored-sonobuoy-sonobuoy/tags

**Comment by masap** [comment]
I got it, thank you.
